name:                slurp
version:             0.1.0.0
github:              "rolsdorph/slurp"
license:             BSD3
author:              "Mads Rolsdorph"
maintainer:          "m.rolsdorph@gmail.com"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rolsdorph/slurp#readme>

dependencies:
- base >= 4.7 && < 5
- cryptohash-md5
- wai
- wai-extra
- warp
- http-types
- bytestring
- convertible
- time
- text
- HDBC
- HDBC-postgresql
- uuid
- req
- utf8-string
- regex-base
- pcre-light
- base16-bytestring
- aeson
- vector
- jose
- lens
- mtl
- hspec
- case-insensitive
- stringsearch
- websockets
- async
- amqp
- hslogger
- http-client
- http-client-tls
- unordered-containers
- containers
- influxdb
- scientific
- modern-uri
- QuickCheck
- stm

library:
  source-dirs: src

executables:
  slurp-exe:
    main:                Main.hs
    source-dirs:         api
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slurp

  hue-metrics-collector-exe:
    main:                Main.hs
    source-dirs:         collector
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slurp

  influx-pusher-exe:
    main:                Main.hs
    source-dirs:         influxpusher
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slurp

  notifier-exe:
    main:                Main.hs
    source-dirs:         notifier
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slurp

tests:
  api-test:
    main:                Spec.hs
    source-dirs:
     - api
     - test/api
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slurp

  google-login-test:
    main:                Spec.hs
    source-dirs:         test/google-login
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slurp

  oauth-test:
    main:                Spec.hs
    source-dirs:         test/oauth
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slurp

  notifier-test:
    main:                Spec.hs
    source-dirs:
      - notifier
      - test/notifier
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - slurp
      - hspec

  collector-test:
    main:                Spec.hs
    source-dirs:
      - collector
      - test/collector
      - test/util
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - slurp
      - hspec

  influx-pusher-test:
    main:                Spec.hs
    source-dirs:
      - influxpusher
      - test/influxpusher
      - test/util
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - slurp
      - hspec

  e2e-test:
    main:                Spec.hs
    source-dirs:
      - test/e2e
      - test/util
      - api
      - collector
      - influxpusher
      - notifier
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - slurp
      - hspec
      - http-conduit
      - directory
      - dotenv
